version: '3.9'
services:
  neo4j:
    image: neo4j:5-community
    container_name: monitor-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      # Set DB auth explicitly; avoid passing NEO4J_USER/PASS into container (they map to invalid config keys)
      NEO4J_AUTH: "neo4j/monitor_pass"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
volumes:
  neo4j-data:
  neo4j-logs:
