version: '3.9'
services:
  neo4j:
    image: neo4j:5-community
    container_name: monitor-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    env_file:
      - .env
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASS}"  # Removed inline defaults
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
volumes:
  neo4j-data:
  neo4j-logs:
