version: '3.9'
services:
  neo4j:
    image: neo4j:5-community
    container_name: monitor-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      # Set DB auth explicitly; avoid passing NEO4J_USER/PASS into container (they map to invalid config keys)
      NEO4J_AUTH: "neo4j/monitor_pass"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  mongo:
    image: mongo:6
    container_name: monitor-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: monitor-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    volumes:
      - qdrant-data:/qdrant/storage

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: monitor-opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  minio:
    image: minio/minio:latest
    container_name: monitor-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"  # Console
    volumes:
      - minio-data:/data

  redis:
    image: redis:7-alpine
    container_name: monitor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  neo4j-data:
  neo4j-logs:
  mongo-data:
  qdrant-data:
  opensearch-data:
  minio-data:
  redis-data:
