[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E","F","I","UP","B","W"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["core"]
force-sort-within-sections = true
